/** UML metadata is semantic; view filters and shapes never change these definitions. */
export interface UmlMultiplicity {
  readonly lower: number
  readonly upper: number | '*'
}
export type UmlVisibility = 'public' | 'private' | 'protected' | 'package'
export type UmlType = { readonly external: string } | { readonly classifier: string }
export type UmlTarget =
  | { readonly element: string; readonly member?: string }
  | { readonly relationship: string; readonly end?: string }
export interface UmlProperties {
  readonly readOnly?: boolean
  readonly ordered?: boolean
  readonly unique?: boolean
  readonly constraints?: readonly string[]
  readonly stereotypes?: readonly string[]
}
export interface UmlNamed extends UmlProperties {
  readonly id: string
  readonly name: string
  readonly description?: string
}
export interface UmlTyped extends UmlProperties {
  readonly type?: UmlType
  readonly multiplicity?: UmlMultiplicity
  readonly default?: string
}
export interface UmlAttribute extends UmlNamed, UmlTyped {
  readonly visibility?: UmlVisibility
  readonly static?: boolean
  readonly derived?: boolean
  readonly redefines?: readonly string[]
  readonly subsets?: readonly string[]
}
export interface UmlParameter extends UmlNamed, UmlTyped {
  readonly direction?: 'in' | 'out' | 'inout' | 'return'
}
export interface UmlOperation extends UmlNamed {
  readonly visibility?: UmlVisibility
  readonly static?: boolean
  readonly abstract?: boolean
  readonly isConstructor?: boolean
  readonly query?: boolean
  readonly parameters?: readonly UmlParameter[]
  readonly returns?: UmlTyped
}
export interface UmlTemplateParameter extends UmlNamed {
  readonly bound?: UmlType
  readonly defaultType?: UmlType
}
export interface UmlTemplateBinding {
  readonly template: string
  readonly arguments: readonly { readonly parameter: string; readonly type: UmlType }[]
}
export interface UmlCompartment extends UmlNamed {
  readonly entries: readonly UmlNamed[]
}
interface UmlClassifierBase extends UmlProperties {
  readonly abstract?: boolean
  readonly attributes?: readonly UmlAttribute[]
  readonly operations?: readonly UmlOperation[]
  readonly templates?: readonly UmlTemplateParameter[]
  readonly bindings?: readonly UmlTemplateBinding[]
  readonly compartments?: readonly UmlCompartment[]
}
export type UmlClassifier =
  & UmlClassifierBase
  & (
    | { readonly kind: 'class' | 'interface' | 'dataType'; readonly literals?: never }
    | { readonly kind: 'enumeration'; readonly literals?: readonly UmlNamed[] }
    | { readonly kind: 'primitiveType' | 'package'; readonly literals?: never }
  )
export interface UmlRelationshipEnd extends UmlProperties {
  readonly id: string
  readonly role?: string
  readonly member?: string
  readonly visibility?: UmlVisibility
  readonly multiplicity?: UmlMultiplicity
  readonly navigability?: 'unspecified' | 'navigable' | 'nonNavigable'
  readonly aggregation?: 'none' | 'shared' | 'composite'
  readonly qualifiers?: readonly UmlAttribute[]
}
export interface UmlBinaryRelationship extends UmlProperties {
  /** Authored identity independent of an autogenerated LikeC4 relationship ID. */
  readonly id: string
  readonly kind: 'association' | 'generalization' | 'realization' | 'dependency'
  readonly source: UmlRelationshipEnd
  readonly target: UmlRelationshipEnd
}
export interface UmlAssociationEnd extends UmlRelationshipEnd {
  readonly element: string
}
export interface UmlAssociation extends UmlNamed {
  readonly ends: readonly UmlAssociationEnd[]
}
export interface UmlAssociationClass {
  readonly id: string
  readonly association: string
  readonly classifier: string
}
export interface UmlGeneralizationSet extends UmlNamed {
  readonly relationships: readonly string[]
  readonly disjoint?: boolean
  readonly complete?: boolean
}
export interface UmlAnnotation extends UmlNamed {
  readonly kind: 'note' | 'comment' | 'constraint'
  readonly text: string
  readonly targets: readonly UmlTarget[]
}
export interface UmlModelExtensions {
  readonly associations?: readonly UmlAssociation[]
  readonly associationClasses?: readonly UmlAssociationClass[]
  readonly generalizationSets?: readonly UmlGeneralizationSet[]
  readonly annotations?: readonly UmlAnnotation[]
}
export interface UmlPresentation {
  readonly hiddenMembers?: readonly string[]
  readonly hiddenCompartments?: readonly string[]
  readonly visibility?: readonly UmlVisibility[]
}
/** Provenance for layout-only junctions, legs and annotation attachments. */
export interface UmlOrigin {
  readonly kind: 'association' | 'associationClass' | 'annotation' | 'generalizationSet'
  readonly id: string
  readonly end?: string
}
export interface UmlDiagnostic {
  readonly severity: 'error' | 'warning'
  readonly code: string
  readonly message: string
  readonly target: UmlTarget
}
