import { defineSlotRecipe } from '@pandacss/dev'
export const classCompartments = defineSlotRecipe({
  className: 'likec4-class',
  slots: ['root', 'header', 'section', 'toggle', 'row'],
  base: {
    root: {
      position: 'relative',
      width: '100%',
      height: '100%',
      overflow: 'hidden',
      fontSize: '14px',
      lineHeight: '20px',
      background: 'var(--likec4-palette-fill)',
      color: 'var(--likec4-palette-hiContrast)',
      border: 'none',
      borderRadius: '6px',
      pointerEvents: 'auto',
    },
    header: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      textAlign: 'center',
      fontWeight: '600',
      fontSize: '16px',
      paddingInline: '16px',
    },
    section: { borderTop: '1px solid color-mix(in srgb, var(--likec4-palette-hiContrast) 20%, transparent)' },
    toggle: {
      appearance: 'none',
      border: 'none',
      borderRadius: '0',
      margin: '0',
      display: 'flex',
      alignItems: 'center',
      gap: '6px',
      fontFamily: 'inherit',
      fontWeight: '500',
      width: '100%',
      height: '28px',
      textAlign: 'left',
      paddingInline: '12px',
      cursor: 'pointer',
      fontSize: '12px',
      color: 'inherit',
      background: 'transparent',
      _hover: { background: 'color-mix(in srgb, var(--likec4-palette-hiContrast) 8%, transparent)' },
      _focusVisible: { outline: '2px solid currentColor', outlineOffset: '-2px' },
    },
    row: {
      padding: '6px 16px',
      whiteSpace: 'pre',
      fontFamily: 'var(--likec4-app-font, sans-serif)',
      _focusVisible: { outline: '2px solid currentColor', outlineOffset: '-2px' },
    },
  },
})
